### ISSUE TITLE
css

### ISSUE THREAD

**Issue by jakecarillon** [jakecarillon/a1111#1]

**Comment by jakecarillon** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/89758395/196855597-7e79e340-56e7-4a0e-8d65-c70b4714f0a7.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/89758395/196855643-bcad7d3f-dc9f-4491-866b-2a553f9f3ffd.png">
<!DOCTYPE html>
<html lang="en">
  <style>
    .wrapper-answer {
      display: flex;
      flex-direction: column-reverse;
    }
  </style>
  <style>
    .wrapper {
      display: flex;
    }
    .box {
      width: 100px;
      height: 100px;
    }
    .blue {
      background-color: blue;
    }
    .red {
      background-color: red;
    }
    .yellow {
      background-color: yellow;
    }
    .answer {
      border-radius: 9999px;
    }
  </style>
  <body>
    <div class="wrapper">
      <div class="box blue"></div>
      <div class="box yellow"></div>
      <div class="box red"></div>
    </div>
    
  </body>
</html>

**Comment by jakecarillon** [comment]
<img width="583" alt="image" src="https://user-images.githubusercontent.com/89758395/196855748-76a6a2f0-1cc4-4ba1-9c75-1cef51db4ae4.png">
<img width="583" alt="image" src="https://user-images.githubusercontent.com/89758395/196855804-c08d11ff-b371-47a6-983a-c984b2e31e92.png">

```css
<!DOCTYPE html>
<html lang="en">
  <style>
    .wrapper-answer {
      display: flex;
      flex-direction: column-reverse;
    }
  </style>
  <style>
    .wrapper {
      display: flex;
    }
    .box {
      width: 100px;
      height: 100px;
    }
    .blue {
      background-color: blue;
    }
    .red {
      background-color: red;
    }
    .yellow {
      background-color: yellow;
    }
    .answer {
      border-radius: 9999px;
    }
  </style>
  <body>
    <!-- <div class="wrapper">
      <div class="box blue"></div>
      <div class="box yellow"></div>
      <div class="box red"></div>
    </div> -->
    <div class="wrapper-answer">
      <div class="box blue answer"></div>
      <div class="box yellow answer"></div>
      <div class="box red answer"></div>
    </div>
  </body>
</html>

```

**Comment by jakecarillon** [comment]
<img width="583" alt="image" src="https://user-images.githubusercontent.com/89758395/196860631-9d2fcf96-7df4-41d7-bd2d-e8cc73724d6c.png">
```css
<!DOCTYPE html>
<html lang="en">
  <style>
    .wrapper-answer {
      display: flex;
      /* flex-direction: column-reverse; */
    }
  </style>
  <style>
    .wrapper {
      display: flex;
      justify-content: space-between;
    }
    .box {
      width: 100px;
      height: 100px;
    }
    .blue {
      background-color: blue;
    }
    .red {
      background-color: red;
    }
    .yellow {
      background-color: yellow;
    }
    .answer {
      border-radius: 9999px;
    }
  </style>
  <body>
    <div class="wrapper">
      <div class="box blue"></div>
      <div class="box yellow"></div>
      <div class="box red"></div>
    </div>
    <!-- <div class="wrapper-answer">
      <div class="box blue answer"></div>
      <div class="box yellow answer"></div>
      <div class="box red answer"></div>
    </div> -->
  </body>
</html>


```

**Comment by jakecarillon** [comment]
<img width="583" alt="image" src="https://user-images.githubusercontent.com/89758395/196860999-f0f297d0-8d09-4db5-9f18-a46ea86d5745.png">



```css

<!DOCTYPE html>
<html lang="en">
  <style>
    .wrapper-answer {
      display: flex;
      /* flex-direction: column-reverse; */
    }
  </style>
  <style>
    .wrapper {
      display: flex;
      flex-flow: column-reverse nowrap;
      align-items: center;
    }
    .box {
      width: 100px;
      height: 100px;
    }
    .blue {
      background-color: blue;
    }
    .red {
      background-color: red;
    }
    .yellow {
      background-color: yellow;
    }
    .answer {
      border-radius: 9999px;
    }
  </style>
  <body>
    <div class="wrapper">
      <div class="box blue"></div>
      <div class="box yellow"></div>
      <div class="box red"></div>
    </div>
    <!-- <div class="wrapper-answer">
      <div class="box blue answer"></div>
      <div class="box yellow answer"></div>
      <div class="box red answer"></div>
    </div> -->
  </body>
</html>

```

**Comment by jakecarillon** [comment]
<img width="583" alt="image" src="https://user-images.githubusercontent.com/89758395/196861939-2e624367-acf3-43d3-98e5-cb3eb3710f8b.png">
<img width="583" alt="image" src="https://user-images.githubusercontent.com/89758395/196862423-f696a263-6d92-46ff-bae9-141ed8c2c5fa.png">



```css

<!DOCTYPE html>
<html lang="en">
  <style>
    .wrapper-answer {
      display: flex;
      /* flex-direction: column-reverse; */
      flex-flow: column-reverse wrap-reverse;
      justify-content: center;
      align-self: stretch;
    }
  </style>
  <style>
    .wrapper {
      height: 100vh;
      display: flex;
      flex-flow: column-reverse wrap-reverse;
      justify-content: center;
      align-content: space-between;
    }
    .box {
      width: 100px;
      height: 100px;
      border: 1px solid;
    }
    .blue {
      background-color: blue;
    }
    .red {
      background-color: red;
    }
    .yellow {
      background-color: yellow;
    }
    .answer {
      border-radius: 9999px;
    }
  </style>
  <body>
    <div class="wrapper">
      <div class="box blue"></div>
      <div class="box yellow"></div>
      <div class="box yellow"></div>
      <div class="box yellow"></div>
      <div class="box yellow"></div>
      <div class="box red"></div>
      <div class="box red"></div>
    </div>
    <!-- <div class="wrapper-answer">
      <div class="box blue answer"></div>
      <div class="box yellow answer"></div>
      <div class="box red answer"></div>
    </div> -->
  </body>
</html>




```

**Comment by jakecarillon** [comment]
<img width="583" alt="image" src="https://user-images.githubusercontent.com/89758395/196862982-90f95f8d-de22-4e57-9f27-ff097c4ad37e.png">

<!DOCTYPE html>
<html lang="en">
  <style>
    .wrapper-answer {
      display: flex;
      /* flex-direction: column-reverse; */
      flex-flow: column-reverse wrap-reverse;
      justify-content: center;
      align-self: stretch;
    }
  </style>
  <style>
    .wrapper {
      height: 90vh;
      display: flex;
      flex-flow: column-reverse wrap-reverse;
      /* justify-content: center; */
      justify-content: flex-start;
      align-content: space-between;
    }
    .box {
      width: 100px;
      height: 100px;
      border: 1px solid;
    }
    .blue {
      background-color: blue;
    }
    .red {
      background-color: red;
    }
    .yellow {
      background-color: yellow;
    }
    .answer {
      border-radius: 9999px;
    }
  </style>
  <body>
    <div class="wrapper">
      <div class="box blue"></div>
      <div class="box yellow"></div>
      <div class="box yellow"></div>
      <div class="box yellow"></div>
      <div class="box yellow"></div>
      <div class="box red"></div>
      <div class="box red"></div>
    </div>
    
  </body>
</html>

**Comment by jakecarillon** [comment]
<img width="583" alt="image" src="https://user-images.githubusercontent.com/89758395/196863058-b81d3258-d35e-4dcd-98d6-dc1c47482c6c.png">


```css
<!DOCTYPE html>
<html lang="en">
  <style>
    .wrapper-answer {
      display: flex;
      /* flex-direction: column-reverse; */
      flex-flow: column-reverse wrap-reverse;
      /* justify-content: center; */
      /* align-self: stretch; */
    }
  </style>
  <style>
    .wrapper {
      height: 90vh;
      display: flex;
      flex-flow: column-reverse wrap-reverse;
      /* justify-content: center; */
      justify-content: flex-end;
      align-content: space-between;
    }
    .box {
      width: 100px;
      height: 100px;
      border: 1px solid;
    }
    .blue {
      background-color: blue;
    }
    .red {
      background-color: red;
    }
    .yellow {
      background-color: yellow;
    }
    .answer {
      border-radius: 9999px;
    }
  </style>
  <body>
    <div class="wrapper">
      <div class="box blue"></div>
      <div class="box yellow"></div>
      <div class="box yellow"></div>
      <div class="box yellow"></div>
      <div class="box yellow"></div>
      <div class="box red"></div>
      <div class="box red"></div>
    </div>
    <!-- <div class="wrapper-answer">
      <div class="box blue answer"></div>
      <div class="box yellow answer"></div>
      <div class="box red answer"></div>
    </div> -->
  </body>
</html>


```
